## SelectK _Classification - Best Model

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.ensemble import RandomForestClassifier
import pickle
import matplotlib.pyplot as plt

In [2]:
def selectkbest(indep_x,dep_y,n):
    SK = SelectKBest(score_func = chi2,k=n)
    SKfit = SK.fit(indep_x,dep_y)
    selectK_features = SKfit.transform(indep_x)
    selected_indices = SKfit.get_support(indices=True) 
    selected_features_names = indep_x.columns[selected_indices]
    return selectK_features, selected_features_names.tolist()

In [3]:
def split_scaler(indep_x,dep_y):
    x_train,x_test,y_train,y_test = train_test_split(indep_x,dep_y,test_size = 0.2,random_state = 0)
    sc = StandardScaler()
    x_train = sc.fit_transform(x_train)
    x_test = sc.transform(x_test)
    return x_train,x_test,y_train,y_test,sc

def cm_prediction(classifier,x_test,y_test):
    y_pred = classifier.predict(x_test)
    cm = confusion_matrix(y_test,y_pred)
    accuracy = accuracy_score(y_test,y_pred)
    clas_report = classification_report(y_test,y_pred)
    return classifier,accuracy

def random(x_train,y_train,x_test,y_test):
    classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state=0)
    classifier.fit(x_train,y_train)
    return cm_prediction(classifier,x_test,y_test)

In [4]:
def selectK_classification(accdc):
    SKdataframe = pd.DataFrame(index = ['Chisquare'], columns = ['Random'])
    SKdataframe['Random'] = accdc
    return SKdataframe

In [5]:
dataset = pd.read_csv("CKD.csv",index_col=None)
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [6]:
df = dataset

In [7]:
df = pd.get_dummies(df,dtype=int,drop_first=True)

In [8]:
df

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [9]:
indep_x = df.drop('classification_yes',axis=1)
dep_y = df['classification_yes']

In [10]:
kbest, selected_features_names = selectkbest(indep_x,dep_y,7)

accdc = []

In [11]:
selected_features_names

['al', 'bgr', 'bu', 'sc', 'hrmo', 'pcv', 'wc']

In [12]:
kbest

array([[3.00000000e+00, 1.48112676e+02, 5.74821053e+01, ...,
        1.25181556e+01, 3.88689024e+01, 8.40819113e+03],
       [2.00000000e+00, 1.48112676e+02, 2.20000000e+01, ...,
        1.07000000e+01, 3.40000000e+01, 1.23000000e+04],
       [1.00000000e+00, 9.90000000e+01, 2.30000000e+01, ...,
        1.20000000e+01, 3.40000000e+01, 8.40819113e+03],
       ...,
       [3.00000000e+00, 1.10000000e+02, 1.15000000e+02, ...,
        9.10000000e+00, 2.60000000e+01, 9.20000000e+03],
       [0.00000000e+00, 2.07000000e+02, 8.00000000e+01, ...,
        8.50000000e+00, 3.88689024e+01, 8.40819113e+03],
       [0.00000000e+00, 1.00000000e+02, 4.90000000e+01, ...,
        1.63000000e+01, 5.30000000e+01, 8.50000000e+03]])

In [13]:
x_train,x_test,y_train,y_test,sc = split_scaler(kbest,dep_y)

In [14]:
classifier,accuracy = random(x_train,y_train,x_test,y_test)
accdc.append(accuracy)

In [15]:
result = selectK_classification(accdc)

In [16]:
result

           Random
Chisquare   0.975

In [17]:
# Create file for the model

filename = 'Finalized_Random_Model.sav'

In [18]:
import pickle as pkl
pickle.dump(classifier,open(filename,'wb'))

In [19]:
# Create file for the preprocessing step

filenamesc = 'sc.pkl'

In [20]:
pickle.dump(sc,open(filenamesc,'wb'))

In [21]:
# Load the Model
sc = pickle.load(open('sc.pkl','rb'))

In [22]:
# Get the User Input 
user_input = sc.transform([[2.0, 148.11, 17, 1.7, 14.6, 52, 6900]])
user_input

array([[ 0.91842938, -0.01533156, -0.82516364, -0.25895875,  0.79130636,
         1.61244852, -0.59094013]])

In [23]:
loaded_model = pickle.load(open('Finalized_Random_Model.sav','rb'))
Prediction = loaded_model.predict(user_input)

In [24]:
Prediction

array([1])