## SelectK Algorithm - Classification

In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import pickle

In [65]:
def selectkbest(indep_x,dep_y,n):
    SK = SelectKBest(score_func = chi2,k=n)
    SKfit = SK.fit(indep_x,dep_y)
    selectK_features = SKfit.transform(indep_x)
    selected_indices = SKfit.get_support(indices=True) 
    selected_features_names = indep_x.columns[selected_indices]
    return selectK_features, selected_features_names.tolist()

def split_scalar(indep_x,dep_y):
    x_train,x_test,y_train,y_test = train_test_split(indep_x, dep_y, test_size=0.2, random_state=0)
    sc = StandardScaler()
    x_train = sc.fit_transform(x_train)
    x_test = sc.transform(x_test)
    return x_train,x_test,y_train,y_test

In [66]:
raw_dataset = pd.read_csv("CKD.csv",index_col=None)
raw_dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [67]:
df = raw_dataset

In [68]:
df = pd.get_dummies(df,dtype=int,drop_first=True)

In [69]:
df

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [70]:
df['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [71]:
indep_x = df.drop('classification_yes', axis = 1)
dep_y = df['classification_yes']

In [80]:
kbest, selected_features_names = selectkbest(indep_x,dep_y,7)

In [81]:
selected_features_names

['al', 'bgr', 'bu', 'sc', 'hrmo', 'pcv', 'wc']

In [82]:
kbest

array([[3.00000000e+00, 1.48112676e+02, 5.74821053e+01, ...,
        1.25181556e+01, 3.88689024e+01, 8.40819113e+03],
       [2.00000000e+00, 1.48112676e+02, 2.20000000e+01, ...,
        1.07000000e+01, 3.40000000e+01, 1.23000000e+04],
       [1.00000000e+00, 9.90000000e+01, 2.30000000e+01, ...,
        1.20000000e+01, 3.40000000e+01, 8.40819113e+03],
       ...,
       [3.00000000e+00, 1.10000000e+02, 1.15000000e+02, ...,
        9.10000000e+00, 2.60000000e+01, 9.20000000e+03],
       [0.00000000e+00, 2.07000000e+02, 8.00000000e+01, ...,
        8.50000000e+00, 3.88689024e+01, 8.40819113e+03],
       [0.00000000e+00, 1.00000000e+02, 4.90000000e+01, ...,
        1.63000000e+01, 5.30000000e+01, 8.50000000e+03]])

In [83]:
kbest.shape

(399, 7)

In [84]:
x_train,x_test,y_train,y_test = split_scalar(kbest,dep_y)

In [85]:
# Define parameter grids for each classifier

params_grid = { 'logistic' : {'penalty' : ['l1', 'l2', 'elasticnet'],
                              'solver' : ['saga'],
                              'multi_class': ['auto', 'ovr', 'multinomial']},
               
              'svm_linear' : {'kernel':['linear'],
                               'C' : [1,10,100,1000,2000,3000]},
               
           'svm_nonlinear' : {'kernel':['linear','rbf','poly','sigmoid'],
                              'C' : [1,10,100,1000,2000,3000], 
                              'gamma' : ['scale','auto']},
               
                     'knn' : {'n_neighbors': [3, 5, 7],
                              'weights': ['uniform', 'distance']},

                    'naive': {},  # Naive Bayes has no hyperparameters to tune
               
                 'decision': {'criterion': ['gini', 'entropy'],
                              'max_depth': [None, 10, 20, 30]},

               'random': {'n_estimators': [50, 100, 200],
                              'max_depth': [None, 10, 20, 30],
                              'criterion': ['gini', 'entropy']}}

In [78]:
# Helper function to run GridSearchCV and return the best estimator and its accuracy

def run_gridsearch(estimator, params, x_train, y_train, x_test, y_test):
    grid_search = GridSearchCV(estimator, params, refit=True, verbose=3, n_jobs=-1, scoring='accuracy')
    grid_search.fit(x_train, y_train)
    best_model = grid_search.best_estimator_
    accuracy = best_model.score(x_test, y_test)
    return best_model, accuracy

In [79]:
run_gridsearch(LogisticRegression(), params_grid['logistic'], x_train, y_train, x_test, y_test)
run_gridsearch(SVC(), params_grid['svm_linear'], x_train, y_train, x_test, y_test)
run_gridsearch(SVC(), params_grid['svm_nonlinear'], x_train, y_train, x_test, y_test)
run_gridsearch(KNeighborsClassifier(), params_grid['knn'], x_train, y_train, x_test, y_test)
run_gridsearch(DecisionTreeClassifier(), params_grid['decision'], x_train, y_train, x_test, y_test)
run_gridsearch(RandomForestClassifier(), params_grid['random'], x_train, y_train, x_test, y_test)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

C:\Anaconda3\envs\AIML\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
15 fits failed out of a total of 45.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AIML\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\envs\AIML\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\envs\AIML\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1182, in fit
    raise ValueError("l1_ratio must be specified when penalty is elasticnet.")
ValueError: l1_ratio must be specified when penalty is elasticnet.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\envs\AIML\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [0.9593254 0.965625        nan 0.9593254 0.965625        nan 0.9624504
 0.9625          nan]
  warnings.warn(
C:\Anaconda3\envs\AIML\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

Fitting 5 folds for each of 6 candidates, totalling 30 fits
Fitting 5 folds for each of 48 candidates, totalling 240 fits
Fitting 5 folds for each of 6 candidates, totalling 30 fits
Fitting 5 folds for each of 8 candidates, totalling 40 fits
Fitting 5 folds for each of 24 candidates, totalling 120 fits

(RandomForestClassifier(max_depth=10, n_estimators=50), 0.9875)

### K = 7 ---> 7 features are the best input for SelectK Algorithm with High Accuracy